apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    test: rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollout
  template:
    metadata:
      labels:
        app: rollout
    spec:
      containers:
        - name: rollout-test
          image: busybox:1.31
          command: ["sh", "-c", "sleep 1000;"]
