apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    component: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    component: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis
  labels:
    app: redis
    component: redis
spec:
  parallelism: 2
  template:
    metadata:
      name: redis
      labels:
        app: redis
        component: redis
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-job
          image: registry.cn-hangzhou.aliyuncs.com/twocat/job-wq-2
