#https://kubernetes.io/docs/tasks/job/parallel-processing-expansion/
#mkdir ./jobs
#for i in apple banana cherry
#do
# cat job-tmpl.yaml | sed "s/\$TIME/$i/" > ./jobs/job-$i.yaml
#done
apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$TIME
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      restartPolicy: Never
      containers:
        - name: jobexample
          image: busybox
          command:
            - sh
            - -c
            - echo processing item $TIME && sleep 5
