apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    app: nginx
    enviroment: production
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80