apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
#  revisionHistoryLimit:
#  paused:
#  progressDeadlineSeconds:
#  minReadySeconds:
#  strategy:
#    rollingUpdate:
#      maxSurge:
#      maxUnavailable:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
