apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  targetCPUUtilizationPercentage: 50
