apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    test: liveness
spec:
  containers:
    - name: liveness
      image: nginx
      livenessProbe:
        httpGet:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
