apiVersion: v1
kind: Pod
metadata:
  name: startup-http
  labels:
    test: startup
spec:
  containers:
    - name: startup
      image: nginx
      command:
        - sh
        - -c
        - sleep 100; nginx -g 'daemon off;';
      startupProbe:
        httpGet:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
        failureThreshold: 40
      livenessProbe:
        httpGet:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
        failureThreshold: 1
