apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      command:
        - redis-sever
        - /redis-master/redis.conf
      ports:
        - containerPort: 6379
      env:
        - name: MASTER
          value: true
      resources:
        limits:
          cpu: '0.1'
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis.conf
    - name: data
      emptyDir: {}
