apiVersion: v1
kind: ConfigMap
metadata:
  name: task-cm-all
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: task-cm-all-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - env
      envFrom:
        - configMapRef:
            name: task-cm-all