apiVersion: v1
kind: ConfigMap
metadata:
  name: task-cm-single
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-cm-env
data:
  log_level: INFO
---
apiVersion: v1
kind: Pod
metadata:
  name: task-configmap-pod-env
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - env
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: task-cm-single
              key: special.how
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: task-cm-pod-multiple
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - env
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: task-cm-single
              key: special.how
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: task-cm-env
              key: log_level
  restartPolicy: Never