apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: task-kustomize-configmap-file
    files:
      - application.properties
  - name: task-kustomize-configmap-literals
    literals:
      - Foo=Bar
secretGenerator:
  - name: task-kustomize-secret-file
    files:
      - pwd.txt
  - name: task-kustomize-secret-literals
    literals:
      - username=admin
      - pwd=secret
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    node: generated