apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: task-kustomize-deployment
    path: patch.yml