apiVersion: v1
kind: Pod
metadata:
  namespace: cpu-example
  name: cpu-demo-1
spec:
  containers:
    - name: cpu-demo-ctr
      image: vish/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
        - -cpus
        - "2"