apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: cpu-example
spec:
  containers:
    - name: cpu-demo-ctr-2
      image: vish/stress
      args:
        - -cpu
        - "2"
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
