version: '3'
services:
  mongo:
    image: mongo:4.2.2
    ports:
    - 27017:27017
  hello-mongo:
    image: registry.cn-hangzhou.aliyuncs.com/twocat/hello-mongo
    command:
      - --spring.data.mongodb.host=mongo
    ports:
    - 8080:8080
