version: '3'
services:
  websocket:
    image: registry.cn-hangzhou.aliyuncs.com/twocat/websocket-redis
    ports:
      - '8080:8080'
    networks:
      - ws-redis
  redis:
    image: 'redis'
    networks:
      - ws-redis
networks:
  ws-redis:
    driver: bridge