apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: registry.cn-hangzhou.aliyuncs.com/twocat/websocket-redis
        - name: redis
          image: redis:latest
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: websocket
