apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-kustomize-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          command:
            - start
            - --host
            - $(MY_SERVICE_NAME)
