apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-kustomize-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              memory: 512Mi