server:
  port: 8070

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:hadoop102,hadoop103,hadoop104:2181