apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: task-ds
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.30
          command:
            - sh
            - -c
            - sleep 1h
