spring:
  application:
    name: nacos-service-consumer
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:10000
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#server:
#  port: 8000
#feign:
#  sentinel:
#    enabled: true