apiVersion: v1
kind: Pod
metadata:
  name: init-pods-lab
  labels:
    app.kubernetes.io/name: init-pods
    app.kubernetes.io/instance: init-pods-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: init
    app.kubernetes.io/part-of: init-pods-lab
spec:
  containers:
    - name: web
      image: busybox
      command: ['sh', '-c', 'echo this app is running && sleep 3600']
  initContainers:
    - name: init-db
      image: busybox
      command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
    - name: init-service
      image: busybox
      command:
        - sh
        - -c
        - 'until nslookup service; do echo waiting for service; sleep 2; done;'
