apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    test: readiness
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - sleep 10; touch /ready; sleep 100;
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - cat /ready
        initialDelaySeconds: 3
        periodSeconds: 3