apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: init-service-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: init-pods-lab
spec:
  selector:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: init-service-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: init-pods-lab
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80