apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app.kubernetes.io/name: wordpress-mysql
    app.kubernetes.io/instance: wordpress-mysql-instance
    app.kubernetes.io/component: db
    app.kubernetes.io/version: "5.7"
    app.kubernetes.io/part-of: wordpress
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      name: tcp
  selector:
    app.kubernetes.io/name: wordpress-mysql
    app.kubernetes.io/instance: wordpress-mysql-instance
    app.kubernetes.io/component: db
    app.kubernetes.io/version: "5.7"
    app.kubernetes.io/part-of: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-pvc
  labels:
    app.kubernetes.io/name: wordpress-mysql
    app.kubernetes.io/instance: wordpress-mysql-instance
    app.kubernetes.io/component: db
    app.kubernetes.io/version: "5.7"
    app.kubernetes.io/part-of: wordpress
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app.kubernetes.io/name: wordpress-mysql
    app.kubernetes.io/instance: wordpress-mysql-instance
    app.kubernetes.io/component: db
    app.kubernetes.io/version: "5.7"
    app.kubernetes.io/part-of: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-mysql
      app.kubernetes.io/instance: wordpress-mysql-instance
      app.kubernetes.io/component: db
      app.kubernetes.io/version: "5.7"
      app.kubernetes.io/part-of: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-mysql
        app.kubernetes.io/instance: wordpress-mysql-instance
        app.kubernetes.io/component: db
        app.kubernetes.io/version: "5.7"
        app.kubernetes.io/part-of: wordpress
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PWD
                  name: mysql-pwd
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: wordpress-mysql-pvc