apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-instance
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/part-of: wordpress
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-instance
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/part-of: wordpress
  ports:
    - port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-instance
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/part-of: wordpress
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-instance
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/part-of: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: wordpress-instance
      app.kubernetes.io/component: frontend
      app.kubernetes.io/version: "4.8"
      app.kubernetes.io/part-of: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
        app.kubernetes.io/instance: wordpress-instance
        app.kubernetes.io/component: frontend
        app.kubernetes.io/version: "4.8"
        app.kubernetes.io/part-of: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PWD
                  name: mysql-pwd
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-pvc
      volumes:
        - name: wordpress-pvc
          persistentVolumeClaim:
            claimName: wordpress-pvc

