apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    test: job
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: busybox
          command:
            - sh
            - -c
            - echo hello;