#https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: v1
kind: Service
metadata:
  name: task-run-app-hpa-apache-php
spec:
  ports:
    - port: 80
  selector:
    app: php-apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-run-app-hpa-apache-php
spec:
  selector:
    matchLabels:
      app: task-run-app-hpa-apache-php
  template:
    metadata:
      labels:
        app: task-run-app-hpa-apache-php
    spec:
      containers:
        - name: task-run-app-hpa-apache-php
          image: registry.cn-hangzhou.aliyuncs.com/twocat/php-apache
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: task-run-app-hpa-apache-php-v1
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-run-app-hpa-apache-php
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: task-run-app-hpa-apache-php-v2
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: test-pod
        target:
          type: AverageValue
          averageValue: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-run-app-hpa-apache-php
