apiVersion: apps/v1
kind: Deployment
metadata:
  name: disvoery-deployment
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/instance: discovery-server
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud
    app.kubernetes.io/component: discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery-server
      app.kubernetes.io/instance: discovery-server
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/part-of: spring-cloud
      app.kubernetes.io/component: discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discovery-server
        app.kubernetes.io/instance: discovery-server
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/part-of: spring-cloud
        app.kubernetes.io/component: discovery
    spec:
      containers:
        - name: discovery-server
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-server
          ports:
            - containerPort: 19000
---
apiVersion: v1
kind: Service
metadata:
    name: disvoery-service
    labels:
      app.kubernetes.io/name: discovery-server
      app.kubernetes.io/instance: discovery-server
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/part-of: spring-cloud
      app.kubernetes.io/component: discovery
spec:
  selector:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/instance: discovery-server
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud
    app.kubernetes.io/component: discovery
  type: LoadBalancer
  ports:
    - port: 19000
      targetPort: 19000
