GET http://localhost:8080/employees
Accept: application/json

###

POST http://localhost:8080/employees/
Content-Type: application/json

{
  "name": "his cat",
  "role": "minion of cat"
}

###
PUT http://localhost:8080/employees/3
Content-Type: application/json

{
  "name": "twocat",
  "role": "minion of cat"
}

###
DELETE localhost:8080/employees/3

###
GET localhost:8080/employees/3
Accept: application/json

###

GET http://localhost:8080/orders
Accept: application/json

###

GET http://localhost:8080/orders/4
Accept: application/json

###
DELETE http://localhost:8080/orders/4/cancel
Accept: application/json

###
PUT http://localhost:8080/orders/4/complete
Accept: application/json

###

