apiVersion: v1
kind: Pod
metadata:
  name: annotation-demo
  labels:
    app: nginx
    tier: frontend
    enviroment: development
  annotations:
    imageRegistry: https://hub.docker.com/
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
