spring:
  application:
    name: hello

eureka:
  client:
    service-url:
      defaultZone: http://server-service:19000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 8080