spring:
  application:
    name: hello

#  spring.application.name=hello
#  eureka.instance.prefer-ip-address=true
#  eureka.instance.instance-id=${eureka.instance.prefer-ip-address}:${server.port}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:19000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 8080