apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx.conf
  labels:
    app: hello
    tier: frontend
data:
  nginx.conf: |-
    upstream hello {
      server backend;
    }
    server {
      listen 80;

      location / {
      proxy_pass http://backend;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: hello
    tier: backend
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: hello
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      tier: backend
  template:
    metadata:
      labels:
        app: hello
        tier: backend
    spec:
      containers:
        - name: hello
          image: registry.cn-hangzhou.aliyuncs.com/twocat/hello
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: hello
    tier: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      volumes:
        - name: conf
          configMap:
            name: nginx.conf
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: conf
          ports:
            - containerPort: 80

