apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-4
  namespace: qos-example
spec:
  containers:
    - name: qos-demo-ctr-4
      image: nginx
      resources:
        requests:
          memory: 200Mi
    - name: qos-demo-ctr-4-2
      image: redis:5.0.7