apiVersion: v1
kind: Pod
metadata:
  namespace: qos-example
  name: qos-demo
spec:
  containers:
    - name: qos-demo-ctr
      image: nginx
      resources:
        limits:
          memory: 200Mi
          cpu: 700m
        requests:
          memory: 200Mi
          cpu: 700m
