apiVersion: v1
kind: Pod
metadata:
  name: task-inject-data-cmd-args-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: debian
      image: debian
      command:
        - sh
      args:
        - -c
        - printenv HOSTNAME KUBERNETES_PORT && echo \$(MESSAGE)
      env:
        - name: MESSAGE
          value: hello world
