#https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api
apiVersion: v1
kind: Pod
metadata:
  name: task-inject-data-dapi-vol-pod
  labels:
    zone: zh-cn
    cluster: hiscat
    rack: rack-22
  annotations:
    build: hiscat
    builder: hiscat
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
      args:
        - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
          sleep 5;
          done;
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
---
apiVersion: v1
kind: Pod
metadata:
  name: task-inject-data-dapi-containerinfo-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
      args:
        - while true; do
            echo -en '\n';
            if [[ -e /etc/containerinfo/cpu_limit ]]; then
              echo -en '\n'; cat /etc/containerinfo/cpu_limit; fi;
            if [[ -e /etc/containerinfo/cpu_request ]]; then
              echo -en '\n'; cat /etc/containerinfo/cpu_request; fi;
            if [[ -e /etc/containerinfo/mem_limit ]]; then
              echo -en '\n'; cat /etc/containerinfo/mem_limit; fi;
            if [[ -e /etc/containerinfo/mem_request ]]; then
              echo -en '\n'; cat /etc/containerinfo/mem_request; fi;
            sleep 10;
          done;
      resources:
        requests:
          memory: 32Mi
          cpu: 125m
        limits:
          memory: 64Mi
          cpu: 250m
      volumeMounts:
        - mountPath: /etc/containerinfo
          name: containerinfo
  volumes:
    - name: containerinfo
      downwardAPI:
        items:
          - path: cpu_limit
            resourceFieldRef:
              containerName: busybox
              resource: limits.cpu
              divisor: 1m
          - path: cpu_request
            resourceFieldRef:
              containerName: busybox
              resource: requests.cpu
              divisor: 1m
          - path: mem_limit
            resourceFieldRef:
              containerName: busybox
              resource: limits.memory
              divisor: 1Mi
          - path: mem_request
            resourceFieldRef:
              containerName: busybox
              resource: requests.memory
              divisor: 1Mi
