#https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
apiVersion: v1
kind: Secret
metadata:
  name: task-inject-data-secret
data:
  username: aGlzY2F0Cg==
  password: aGlzY2F0aGlzY2F0MDQwOQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: task-inject-data-secret-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: task-inject-data-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: task-inject-data-secret-env-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: task-inject-data-secret
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: task-inject-data-secret
      envFrom:
        - secretRef:
            name: task-inject-data-secret
          prefix: ALL_
