apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app.kubernetes.io/name: discovery-client
    app.kubernetes.io/instance: discovery-client
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery-client
    app.kubernetes.io/part-of: spring-cloud

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery-client
      app.kubernetes.io/instance: discovery-client
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/component: discovery-client
      app.kubernetes.io/part-of: spring-cloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discovery-client
        app.kubernetes.io/instance: discovery-client
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: discovery-client
        app.kubernetes.io/part-of: spring-cloud
    spec:
      containers:
        - name: discovery-client
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-client
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app.kubernetes.io/name: discovery-client
    app.kubernetes.io/instance: discovery-client
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery-client
    app.kubernetes.io/part-of: spring-cloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discovery-client
    app.kubernetes.io/instance: discovery-client
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery-client
    app.kubernetes.io/part-of: spring-cloud
  ports:
    - port: 8080
      targetPort: 8080