apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-instance
    app.kubernetes.io/component: client
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud-labs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: client
      app.kubernetes.io/instance: client-instance
      app.kubernetes.io/component: client
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/part-of: spring-cloud-labs
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
        app.kubernetes.io/instance: client-instance
        app.kubernetes.io/component: client
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/part-of: spring-cloud-labs
    spec:
      containers:
        - name: client
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-client
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA.SERVER
              value: --eureka.client.serviceUrl.defaultZone=http://server-service:19000/eureka
          command:
            - sh
            - -c
            - java ${JAVA_OPTS} -cp /app/resources:app/classes:app/libs com.hiscat.springdiscoveryclient.SpringDiscoveryClientApplication ${EUREKA.SERVER}
