apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-instance
    app.kubernetes.io/component: discovery
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud-labs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: server-instance
      app.kubernetes.io/component: discovery
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/part-of: spring-cloud-labs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: server-instance
        app.kubernetes.io/component: discovery
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/part-of: spring-cloud-labs
    spec:
      containers:
        - name: server
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-server
          ports:
            - containerPort: 19000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-instance
    app.kubernetes.io/component: discovery
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud-labs
spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-instance
    app.kubernetes.io/component: discovery
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: spring-cloud-labs
  type: NodePort
  ports:
    - port: 19000
      targetPort: 19000