apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-client-deployment
  labels:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: server-client-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: spring-cloud
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discovery
        app.kubernetes.io/instance: server-client-instance
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: discovery
        app.kubernetes.io/part-of: spring-cloud
    spec:
      containers:
        - name: server
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-server
          imagePullPolicy: Always
          ports:
            - containerPort: 19000
        - name: client
          image: registry.cn-hangzhou.aliyuncs.com/twocat/spring-discovery-client
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: server-client-service
  labels:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: server-client-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: spring-cloud
spec:
  selector:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: server-client-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: spring-cloud
  type: LoadBalancer
  ports:
    - port: 19000
      targetPort: 19000
      name: server-port
