#访问无头服务，通过serviceName.namepsace.svc.cluster.local，会自动负载均衡
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  clusterIP: 'None'
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: 'web'
  volumeClaimTemplates:
    - metadata:
        name: nfs
      spec:
        resources:
          requests:
            storage: '3Gi'
        storageClassName: 'nfs'
        accessModes: ['ReadWriteOnce']
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nfs
