apiVersion: v1
kind: Pod
metadata:
  name: static-pv-pvc
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
      args:
        - -c
        - touch /mnt/test-static-pv-pvc/$RANDOM && exit 0 || exit 1
      volumeMounts:
        - mountPath: /mnt/test-static-pv-pvc
          name: static-pvc
  volumes:
    - name: static-pvc
      persistentVolumeClaim:
        claimName: static-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Mi
  nfs:
    path: /mnt/sharedfolder
    server: 192.168.2.40