apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
spec:
  subdomain: subdomian
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
spec:
  subdomain: subdomian
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
