#https://hub.docker.com/_/mysql
version: '3.1'

services:
  db:
    image: mysql:5.7.29
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Xiebo0409

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080