#kubectl get nodes --show-labels
#kubectl label nodes k8s-node1 disktype=ssd
apiVersion: v1
kind: Pod
metadata:
  name: task-assign-pod-1
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: task-assign-pod-node-name
spec:
  nodeName: k8s-node2
  containers:
    - name: nginx
      image: nginx
