apiVersion: v1
kind: Namespace
metadata:
  name: mem-example
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  containers:
    - name: memory-demo-ctr
      image: registry.cn-hangzhou.aliyuncs.com/polinux/stress
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 200Mi
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - 150M
        - --vm-hang
        - "1"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: mem-example
  name: memory-demo-2
spec:
  containers:
    - name: memory-demo-ctr-2
      image: registry.cn-hangzhou.aliyuncs.com/polinux/stress
      resources:
        requests:
          memory: 50Mi
        limits:
          memory: 100Mi
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - 250M
        - --vm-hang
        - "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
  namespace: mem-example
spec:
  containers:
    - name: memory-demo-ctr-3
      image: registry.cn-hangzhou.aliyuncs.com/polinux/stress
      resources:
        limits:
          memory: 1000Gi
        requests:
          memory: 1000Gi
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - 250M
        - --vm-hang
        - "1"
