apiVersion: v1
kind: Pod
metadata:
  name: task-probes-cmd
spec:
  containers:
    - name: task-probes-containers
      image: busybox
      args:
        - sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600;
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: task-probes-http
spec:
  containers:
    - name: task-probes-containers
      image: gcr.azk8s.cn/google-containers/liveness
      args:
        - /server
      livenessProbe:
        httpGet:
          port: 8080
          path: /healthz
          httpHeaders:
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: task-probes-tcp
spec:
  containers:
    - name: task-probes-containers
      image: nginx
      command:
        - sh
        - -c
        - sleep 30; nginx -g "daemon off;"
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 1
