# kubectl create secret generic regcred \
#    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
#    --type=kubernetes.io/dockerconfigjson
# kubectl create secret docker-registry regcred --docker-server=<your-registry-server> \
# --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
apiVersion: v1
kind: Secret
metadata:
  name: task-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJ0d29jYXQwNDA5IiwicGFzc3dvcmQiOiJYaWVibzA0MDkiLCJhdXRoIjoiZEhkdlkyRjBNRFF3T1RwWWFXVmliekEwTURrPSJ9fX0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  name: task-secret-pod
spec:
  imagePullSecrets:
    - name: task-secret
  containers:
    - name: hello
      image: registry.cn-hangzhou.aliyuncs.com/twocat/hello
