apiVersion: v1
kind: Secret
metadata:
  name: task-sa-image-pull-pk
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmNuLWhhbmd6aG91LmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6InR3b2NhdDA0MDkiLCJwYXNzd29yZCI6IlhpZWJvMDQwOSIsImVtYWlsIjoic21haWxYaWVAMTYzLmNvbSIsImF1dGgiOiJkSGR2WTJGME1EUXdPVHBZYVdWaWJ6QTBNRGs9In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
imagePullSecrets:
  - name: task-sa-image-pull-pk
---
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Pod
metadata:
  name: task-sa-pod
spec:
  serviceAccountName: build-robot
  automountServiceAccountToken: false
  nodeName: k8s-node2
  containers:
    - name: task-sa-container
      image: registry.cn-hangzhou.aliyuncs.com/twocat/hello
---
#This ServiceAccountTokenVolumeProjection is beta in 1.12 and enabled by passing all of the following flags to the API server:
#--service-account-issuer
#--service-account-signing-key-file
#--service-account-api-audiences
apiVersion: v1
kind: Pod
metadata:
  name: task-sa-nginx
spec:
  serviceAccountName: build-robot
  containers:
    - name: task-sa-container
      image: nginx
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: vault-token
  volumes:
    - name: vault-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 7200
              audience: vault
