apiVersion: v1
kind: Pod
metadata:
  name: task-security-context-pod
spec:
  containers:
    - name: task-security-context-container
      image: busybox
      command:
        - sleep
        - 1h
      volumeMounts:
        - mountPath: /data/demo
          name: sec-ctx-vol
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: sec-ctx-vol
      emptyDir: {}
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsGroup: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: task-sec-ctx-pod-2
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: task-sec-ctx-container
      image: busybox
      securityContext:
        runAsUser: 0
      command:
        - sleep
        - 1h
---
apiVersion: v1
kind: Pod
metadata:
  name: task-sec-ctx-pod-3
spec:
  containers:
    - name: task-sex-ctx-container-3
      image: busybox
      command:
        - sleep
        - 1h
---
apiVersion: v1
kind: Pod
metadata:
  name: task-sec-ctx-pod-4
spec:
  containers:
    - name: task-sec-ctx-container-4
      image: busybox
      command:
        - sleep
        - 1h
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_TIME
