apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskQueue
      component: rabbitmq
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
        - image: rabbitmq
          name: rabbitmq
          ports:
            - containerPort: 5672
          resources:
            limits:
              cpu: 100m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: task-job-coarse-parallel
  labels:
    component: rabbitmq
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: task-job-coarse-parallel
      labels:
        component: rabbitmq
    spec:
      restartPolicy: OnFailure
      containers:
        - name: task-job-coarse-parallel
          image: registry.cn-hangzhou.aliyuncs.com/twocat/job-wq-1
          env:
            - name: BROKDER_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: QUEUE
              value: job1