apiVersion: v1
kind: Service
metadata:
  name: hello-redis
  labels:
    app: hello-redis
    tier: web-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: hello-redis
    tier: web-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-redis
  labels:
    app: hello-redis
    tier: web-service
spec:
  selector:
    matchLabels:
      app: hello-redis
      tier: web-service
  template:
    metadata:
      labels:
        app: hello-redis
        tier: web-service
    spec:
      containers:
        - name: hello-redis
          image: registry.cn-hangzhou.aliyuncs.com/twocat/hello-redis
          args:
            - --spring.redis.host=redis
