apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: hello-redis
    tier: storage
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: tcp
  selector:
    app: hello-redis
    tier: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: hello-redis
    tier: storage
spec:
  selector:
    matchLabels:
      app: hello-redis
      tier: storage
  template:
    metadata:
      labels:
        app: hello-redis
        tier: storage
    spec:
      containers:
        - name: redis
          image: redis:5.0.7
          ports:
            - containerPort: 6379
