apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: nginx
      image: nginx
#  distype=ssd,
#  kubernetes.io/hostname=k8s-node1,
#  beta.kubernetes.io/arch=amd64,
#  beta.kubernetes.io/os=linux,
#  kubernetes.io/os=linux
#  kubernetes.io/arch=amd64,
